# Generated by Django 3.0.6 on 2020-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=112)),
                ('email', models.EmailField(max_length=112)),
                ('phone', models.PositiveIntegerField(max_length=12)),
                ('msg', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
